services:
  mvp-api-principal:
    build:
      context: ../mvp-api-principal
      dockerfile: Dockerfile
    container_name: mvp-api-principal
    ports:
      - "8000:8000"
    volumes:
      - ../mvp-api-principal/database:/app/database
    networks:
      - garage-bridge

  garage-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: garage-frontend
    depends_on:
      - mvp-api-principal
    ports:
      - "8080:80"
    networks:
      - garage-bridge

networks:
  garage-bridge:
    driver: bridge
